# timings.py

CAPCUT_STARTUP = 3.0
WINDOW_PREPARE = 1.5
CREATE_PROJECT_DELAY = 2.0

IMPORT_OPEN_DELAY = 3.5
IMPORT_SELECTION_DELAY = 1.5
IMPORT_CONFIRM_DELAY = 3

TIMELINE_IMPORT_WAIT = 3.5
TIMELINE_CLICK_DELAY = 1.5

ENHANCE_CLICK_DELAY = 1.0
SUBTITLES_CLICK_DELAY = 5

RETOUCH_DELAY = 1.0
AUDIO_DELAY = 0.8

EXPORT_WINDOW_DELAY = 1.5
EXPORT_NAME_FIELD_DELAY = 0.8
EXPORT_START_DELAY = 2.0
EXPORT_FINISH_WAIT = 8.0
EXPORT_POPUP_DELAY = 1.5
PROJECT_CLOSE_DELAY = 6.0